
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../../../../shared/services/auth_service.dart';
import '../../../../shared/widgets/glass_container.dart';
import '../../../../shared/widgets/glass_text_field.dart';
import '../../../../shared/widgets/glass_dropdown.dart';
import '../../../../shared/widgets/glass_date_picker.dart';
import '../models/correction_request.dart';
import '../services/attendance_correction_service.dart';
import '../../../../shared/widgets/custom_dialog.dart'; // Added Import

class CorrectionRequestForm extends StatefulWidget {
  final VoidCallback onSuccess;
  final DateTime? initialDate; // Added

  const CorrectionRequestForm({super.key, required this.onSuccess, this.initialDate});

  @override
  State<CorrectionRequestForm> createState() => _CorrectionRequestFormState();
}

class _CorrectionRequestFormState extends State<CorrectionRequestForm> {
  late AttendanceCorrectionService _service;
  bool _isLoading = false;

  // Form State
  late DateTime _requestDate; // Changed to late
  CorrectionType _type = CorrectionType.missedPunch;
  CorrectionMethod _method = CorrectionMethod.fix;
  final TextEditingController _reasonController = TextEditingController();
  
  // Method: Fix/Reset
  TimeOfDay? _timeIn;
  TimeOfDay? _timeOut;

  // Method: Add Session (List of maps)
  List<Map<String, TimeOfDay>> _sessions = [];

  @override
  void initState() {
    super.initState();
    _requestDate = widget.initialDate ?? DateTime.now(); // Initialize with passed date
    final authService = Provider.of<AuthService>(context, listen: false);
    _service = AttendanceCorrectionService(authService);
  }

  Future<void> _submit() async {
    if (_reasonController.text.isEmpty) {
      await CustomDialog.show(
        context: context,
        title: "Reason Required",
        message: "Please provide a reason for this correction request so approvers can understand the context.",
        positiveButtonText: "Okay",
        onPositivePressed: () => Navigator.pop(context),
        icon: Icons.warning_amber_rounded,
        iconColor: Colors.orange,
      );
      return;
    }

    if (_method == CorrectionMethod.fix && (_timeIn == null || _timeOut == null)) {
      await CustomDialog.show(
        context: context,
        title: "Missing Timings",
        message: "Please select both 'Time In' and 'Time Out' to proceed with the correction.",
        positiveButtonText: "Okay",
        onPositivePressed: () => Navigator.pop(context),
        icon: Icons.access_time, // Or warning
        iconColor: Colors.orange,
      );
      return;
    }

    if (_method == CorrectionMethod.addSession && _sessions.isEmpty) {
       await CustomDialog.show(
        context: context,
        title: "No Sessions Added",
        message: "Please add at least one session interval to submit this request.",
        positiveButtonText: "Okay",
        onPositivePressed: () => Navigator.pop(context),
        icon: Icons.playlist_add,
        iconColor: Colors.orange,
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final request = AttendanceCorrectionRequest(
        id: '', // Generated by backend
        userId: '', // Handled by backend/service
        userName: '',
        requestDate: _requestDate,
        type: _type,
        method: _method,
        reason: _reasonController.text,
        requestedTimeIn: _timeIn?.format(context),
        requestedTimeOut: _timeOut?.format(context),
        requestedSessions: _sessions.map((s) => {
          'time_in': s['in']!.format(context),
          'time_out': s['out']!.format(context),
        }).toList(),
      );

      await _service.submitCorrectionRequest(request);
      
      widget.onSuccess();
      // Success is likely handled by parent closing/showing success, 
      // but if we need a toast, CustomDialog might be too heavy?
      // User said "remove default flutter popups completely".
      // Parent (Dialog wrapper) usually shows Success Dialog on valid return.
      // So here we do nothing or let parent handle.
      
    } catch (e) {
      await CustomDialog.show(
        context: context,
        title: "Submission Failed",
        message: e.toString(),
        positiveButtonText: "Close",
        onPositivePressed: () => Navigator.pop(context),
        icon: Icons.error_outline,
        iconColor: Colors.red,
        isDestructive: true,
      );
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _pickTime(bool isTimeIn) async {
    final picked = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.now(),
    );
    if (picked != null) {
      setState(() {
        if (isTimeIn) _timeIn = picked;
        else _timeOut = picked;
      });
    }
  }

  // Helper for formatting TimeOfDay
  String _formatTime(TimeOfDay? time) {
    if (time == null) return 'Select Time';
    return time.format(context);
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primaryColor = Theme.of(context).primaryColor;
    final textColor = isDark ? Colors.white : Colors.black87;
    
    // Add border in Dark Mode to distinguish inputs from dialog background
    final BoxBorder? inputBorder = isDark 
        ? Border.all(color: Colors.white.withValues(alpha: 0.1), width: 1)
        : null;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Date
          Text('Date', style: GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w600, color: Colors.grey)),
          const SizedBox(height: 8),
          InkWell(
            onTap: () async {
              await showDialog(
                context: context,
                builder: (context) => GlassDatePicker(
                  initialDate: _requestDate,
                  firstDate: DateTime(2020),
                  lastDate: DateTime.now(),
                  onDateSelected: (date) => setState(() => _requestDate = date),
                ),
              );
            },
            child: GlassContainer(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
              border: inputBorder, // Apply border
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    DateFormat('MMM dd, yyyy').format(_requestDate),
                    style: GoogleFonts.poppins(color: textColor, fontSize: 14),
                  ),
                  Icon(Icons.calendar_today, size: 18, color: isDark ? Colors.white70 : Colors.grey),
                ],
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Type
          GlassDropdown<CorrectionType>(
            value: _type,
            items: CorrectionType.values.map((e) => DropdownMenuItem(
              value: e,
              child: Text(
                e.toString().split('.').last.toUpperCase(),
                style: GoogleFonts.poppins(color: textColor),
              ),
            )).toList(),
            onChanged: (val) => setState(() => _type = val!),
            label: 'Correction Type',
            border: inputBorder, // Apply border
          ),
          const SizedBox(height: 16),

          // Method
          GlassDropdown<CorrectionMethod>(
            value: _method,
            items: CorrectionMethod.values.map((e) => DropdownMenuItem(
              value: e,
              child: Text(
                e.toString().split('.').last.toUpperCase(),
                style: GoogleFonts.poppins(color: textColor),
              ),
            )).toList(),
            onChanged: (val) => setState(() => _method = val!),
            label: 'Action Method',
            border: inputBorder, // Apply border
          ),
          const SizedBox(height: 24),

          // Dynamic Fields
          if (_method == CorrectionMethod.fix || _method == CorrectionMethod.reset) ...[
            Text('Corrected Timings', style: GoogleFonts.poppins(fontWeight: FontWeight.w600, color: textColor)),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: GlassContainer(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14), // Match Date Padding
                    border: inputBorder, 
                    child: InkWell(
                      onTap: () => _pickTime(true),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            _formatTime(_timeIn),
                            style: GoogleFonts.poppins(fontWeight: FontWeight.w500, color: textColor),
                          ),
                          Icon(Icons.access_time, size: 18, color: isDark ? Colors.white70 : Colors.grey),
                        ],
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: GlassContainer(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14), // Match Date Padding
                    border: inputBorder, 
                    child: InkWell(
                      onTap: () => _pickTime(false),
                      child: Row(
                         mainAxisAlignment: MainAxisAlignment.spaceBetween,
                         children: [
                           Text(
                             _formatTime(_timeOut),
                             style: GoogleFonts.poppins(fontWeight: FontWeight.w500, color: textColor),
                           ),
                           Icon(Icons.access_time, size: 18, color: isDark ? Colors.white70 : Colors.grey),
                         ],
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
          
          if (_method == CorrectionMethod.addSession) ...[
             Text('Sessions', style: GoogleFonts.poppins(fontWeight: FontWeight.w600, color: textColor)),
             ..._sessions.asMap().entries.map((entry) {
               final index = entry.key;
               final session = entry.value;
               return Padding(
                 padding: const EdgeInsets.symmetric(vertical: 8.0),
                 child: Row(
                   children: [
                     Text(
                        '${session['in']!.format(context)} - ${session['out']!.format(context)}',
                        style: GoogleFonts.poppins(color: textColor),
                     ),
                     const Spacer(),
                     IconButton(icon: const Icon(Icons.delete, color: Colors.red), onPressed: () {
                       setState(() => _sessions.removeAt(index));
                     })
                   ],
                 ),
               );
             }),
             ElevatedButton(
               onPressed: () async {
                 TimeOfDay? tIn = await showTimePicker(context: context, initialTime: const TimeOfDay(hour: 9, minute: 0), helpText: 'Session Start');
                 if (tIn == null) return;
                 if (!context.mounted) return;
                 TimeOfDay? tOut = await showTimePicker(context: context, initialTime: const TimeOfDay(hour: 13, minute: 0), helpText: 'Session End');
                 if (tOut == null) return;
                 
                 setState(() {
                   _sessions.add({'in': tIn, 'out': tOut});
                 });
               },
               child: const Text('Add Session'),
             ),
          ],

          const SizedBox(height: 24),
          
          GlassTextField(
            controller: _reasonController,
            hintText: 'Reason for correction...',
            maxLines: 3,
            border: inputBorder, // Apply border
          ),
          const SizedBox(height: 24),

          ElevatedButton(
            onPressed: _isLoading ? null : _submit,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF4F46E5), // User Specified Color
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            child: _isLoading 
                ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                : Text('Submit Request', style: GoogleFonts.poppins(fontWeight: FontWeight.bold, color: Colors.white)),
          ),
        ],
      ),
    );
  }
}
